version: '3'

services:
  backend:
    build: ./python-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"
    # depends-on:
    #   - backend

